name: giahdooni
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^6.1.1
  stacked: ^2.0.4
  get: ^4.1.4
  firebase_core: ^1.0.3
  firebase_storage: ^8.0.3
  image_picker: ^0.7.5+3
  top_snackbar_flutter: ^1.0.0
  permission_handler: ^8.0.0+2
  path: ^1.8.0
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.5
  flutter_typeahead: ^1.7.0
  
 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/giahh.png
    - images/zamofilia.jpg
    - images/petus.jpg
    - images/sansoria.jpg
    - images/anjiri.jpg
    - images/ghashoghi.jpg
    - images/agloo.jpg
    - images/nakhl.jpg
    - images/hosnn.jpg
    - images/bent.jpg
    - images/radiator.jpg
    - images/bonsay.jpg
    - images/Ficus.jpg
    - images/Schefflera.jpg
    - images/StringOfPearls.jpg
    - images/swordfern.jpg
    - images/leaf-spot-disease.jpg
    - images/alternalia.jpg
    - images/coldinjury.jpg
    - images/leafyellow.jpg
    - images/bacterial_leaf_spot.jpg
    - images/root_rot.png
    - images/stem_rot.jpg
    - images/no_pic.png
    
    
    
    